### ISSUE TITLE
Hahahaha

### ISSUE THREAD

**Issue by UwUsheep** [NyakoFox/cropped#1]
Hate how there are people like you who want to steal my knee caps when you actually know it's a crime, I can make way more threats than you think, how are you gonna steal my knee caps when you can't find me huh? That just makes you look stupid, I don't know why you mod makers do this but I think it's not funny, you think Fabric is the best, when ahem, the mods that are most popular, hmmm Pixelmon? Ice and Fire? Alex's mobs? Tinker's construct? Well, funny how you say there are more mods, when the better mods are ported to Forge, so don't even think about calling forge bad, because, I will slice you to pieces, which is actually true, considering we have a real Samurai sword in our house. Also I can make even worse threats like well, let's say, snapping your neck, cut your head off, and you still want to steal my knee caps huh? Wow, how weird of you to say that. Just saying, mark my word, I ain't no drama queen but I do know Mojang so I could tell em straight up about how modders like you tell others to die considering you can't take my spleen or steal my knee caps. Furthermore I'd say go to hell.

**Comment by NyakoFox** [comment]
bro you got a math test tomorrow

**Comment by NyakoFox** [comment]
also for anyone stumbling across this: the stupid "if you ask for forge i'll steal your kneecaps" is a _joke_, and I didn't think it was possible for anyone to even process it as a real threat because of how stupid it is. this user definitely has some other issues and it doesn't involve me.

**Comment by youmukonpaku1337** [comment]
it looks like a copypasta lmao
